import { ref, push ,getDatabase, set } from 'firebase/database';

// Function to add a new todo for a specific user
const addTodoToDB = (uid, title, desc) => {
    const db = getDatabase();
    const userTodosRef = ref(db, `todos/${uid}`);

    // Generate a new key for the todo
    const newTodoRef = push(userTodosRef);

    // Get the unique ID generated by push()
    const todoId = newTodoRef.key;

    // Set the todo data along with the todo ID
    set(newTodoRef, {
        id: todoId, 
        title: title,
        description: desc
    }).then(() => {
        console.log("Todo added successfully!");
    }).catch((error) => {
        console.error("Error adding todo:", error);
    });
}

export default addTodoToDB;
